account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'
urlpatterns = [
    path('logout/', auth_views.logout, {'template_name': 'account/logout.html'}, name='logout'),
    path('redirect/', views.login_after_redirect),
    path('settings/', views.user_settings, name='settings')
]

core/urls.py
from django.urls import path

from . import views
from account.views import users as views_user

app_name = 'core'
urlpatterns = [
    path('', views.top),
    path('send/tool/', views.send_item, name='tool'),
    path('send/money/', views.send_money, name='money'),
    path('<slug:username>/', views_user, name='users'),
]

trader/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('social_django.urls', namespace='social')),
    path('account/', include('account.urls')),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.4/css/mdb.min.css" rel="stylesheet">
    <!-- toastr -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
    <link rel="shortcut icon" href="/static/img/favicon.ico">
    <meta property="og:site_name" content="">
    <meta content="@ugo_competio" name="twitter:site">
    <meta content="" name='keywords'>
    {% if top %}
    <meta property="og:type" content="website"/>
    <title>Search(サーチ) - なんとなく検索エンジンっぽいツイッタークライアント</title>
    <meta name="description"        content="デザインがなんとなく検索エンジンっぽいツイッタークライアントです。なんとなくツイッターをやりづらい雰囲気な場所で使えるかもしれません">
    <meta property="og:title"       content="Search(サーチ) - なんとなく検索エンジンっぽいツイッタークライアント">
    <meta property="og:description" content="デザインがなんとなく検索エンジンっぽいツイッタークライアントです。なんとなくツイッターをやりづらい雰囲気な場所で使えるかもしれません">
    <meta property="og:url"         content="{{ request.build_absolute_uri }}">
    <meta name="twitter:card"       content="summary_large_image">
    <meta property="og:image"       content="https://search.altwug.net/static/og.png">
    {% else %}
    <title>{% block title %}{% endblock %} | Search(サーチ)</title>
    <meta property="og:type" content="article"/>
    <meta name="description"        content="{% block description %}{% endblock %}">
    <meta property="og:title"       content="{% block og_title %}{% endblock %} | ">
    <meta property="og:description" content="{% block og_description %}{% endblock %}">
    <meta property="og:url"         content="{{ request.build_absolute_uri }}">
    <meta name="twitter:card"       content="summary_large_image">
    <meta property="og:image"       content="{% block og_image %}{% endblock %}">
    {% endif %}
    {% if page_obj %}
    {% if page_obj.has_previous %}<link rel="prev" href="?page={{ page_obj.previous_page_number }}" />{% endif %}
    {% if page_obj.has_next %}<link rel="next" href="{{ request.build_absolute_uri }}?page={{ page_obj.next_page_number }}" />{% endif %}
    {% endif %}
    <style media="screen">
        body {
            margin-top: 100px;
        }
        .text-small {
            font-size: small;
        }
        .text-md {
            font-size: 20px;
        }
        .text-lg {
            font-size: 36px;
        }
    </style>
    {% block head %}{% endblock %}
</head>
<body>
    {% include "nav.html" %}

    <div class="container mb-5">
        {% block content %}{% endblock %}
    </div>

    <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.13.0/umd/popper.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.4/js/mdb.min.js"></script>
    <!--toastr-->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script>
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
    {% for message in messages %}
    <script>
        $(function () {
            toastr.options = {
                "positionClass": "toast-bottom-right",
            };
            toastr['{{ message.tags }}']('{{ message }}')
        })
    </script>
    {% endfor %}
    {% block script %}{% endblock %}
</body>
</html>

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark stylish-color-dark fixed-top scrolling-navbar">
    <a class="navbar-brand" href="/">貿易ゲーム</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="https://twitter.com/ugo_compeito">twitter</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" id="themes">@{{ user.username }} {{ user.money }}円 <span class="caret"></span></a>
                    <div class="dropdown-menu" aria-labelledby="themes">
                        <a class="dropdown-item" href="{% url 'core:users' user.username %}">マイページ</a>
                        <a class="dropdown-item" href="{% url 'account:settings' %}">ユーザー設定</a>
                        <a class="dropdown-item" href="{% url 'account:logout' %}">ログアウト</a>
                        {% if user.is_superuser %}
                        <a class="dropdown-item" href="/admin/">管理画面</a>
                        {% endif %}
                  </div>
                </li>
                {% else %}
                <a class="btn btn-info" href="{% url 'social:begin' 'twitter' %}?next={{ request.path }}">ツイッターでログイン</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>

templates/temp.html
{% extends "base.html" %}

{% block title %}{% endblock %}
{% block description %}{% endblock %}
{% block og_title %}{% endblock %}
{% block og_description %}{% endblock %}
{% block og_image %}{% endblock %}
{% block head %}{% endblock %}

{% block content %}

{% endblock %}

{% block script %}{% endblock %}